### ISSUE TITLE
Subscription Service aiio docker compose

### ISSUE THREAD

**Issue by Papadakni** [ScorpioBroker/ScorpioBroker#225]
I am running scorpio with the default configuration, following the building and installation guide, using docker compose and the almost all in one .yml file, for testing purposes. I noticed that I could not get subscriptions to work, and at first I thought it had to do with misconceptions I had with the ngsi-ld api. 
However I realised while looking at scorpio/v1/info/health/ that the subscription service is not running.

![image](https://user-images.githubusercontent.com/10787842/119547530-e25a0e80-bd9d-11eb-8a81-39187cfba6a5.png)

I tried doing the whole process from scratch on different remote vms but with the same problem. 
Regular ngsi-ld commands seem to be working fine.
Appreciate your time.

**Comment by arpitNEC** [comment]
hello @Papadakni ,

Hope you are doing good,
I used this [docker-compose file](https://github.com/ScorpioBroker/ScorpioBroker/blob/development/docker-compose-aaio.yml)  for the deployment and it's working fine for me.
Please try this file for deployment, and if the issue remains the same please do let me know.
 
![Screenshot 2021-05-26 113003](https://user-images.githubusercontent.com/64079608/119609765-c003d780-be15-11eb-8c79-861b506439cd.png)

**Comment by Papadakni** [comment]
Hello and thanks for the quick reply, I tried the file you sent but for some reason I still have the same issue :/ 
![image](https://user-images.githubusercontent.com/10787842/119697178-97510180-be58-11eb-9938-6bf89d3002a4.png)
Thanks again for your time.

**Comment by arpitNEC** [comment]
hello @Papadakni ,

I have gone through the same scenario and figured out that yes subscription manager has some issue in it and we have started working on fixing the same. In the meanwhile, you can use the **scorpiobroker/scorpio:scorpio-aaio_1.0.5** docker image instead of scorpiobroker/scorpio:scorpio-aaio_latest docker image in the docker-compose I have tested that image, and it's working fine. You may still get Not running status but please try to make the subscription request it will surely work.
Sorry for the inconvenience.
Please do reach out if this thing not work.

**Comment by ajayyadavnec** [comment]
Please open the issue if you still face the problem
