### ISSUE TITLE
Multi-tenant implementation

### ISSUE THREAD

**Issue by subhommitra** [ScorpioBroker/ScorpioBroker#267]
I can see in release history and github issues that multi-tenant support has been implemented in Scorpio. However, I am not seeing any explanation of this in the documentation. Can someone please explain how multi-tenancy has been implemented (for e.g., separate DBs, etc.) and what changes should we make to the API payloads to take advantage of this (e.g. I think this is related to fiware headers but I am not sure, some explanation would be greatly appreciated).

**Comment by amitrnec** [comment]
Hi,
As we have implemented multi tenant 
We have created new database  in POSTGRESQL for each tenant so the data goes into the respective tenant DB. 
for example if we provided the http header  key "NGSILD-Tenant"  and value "urn:ngsi-ld:Example:tenant1 then it would be DB urn:ngsi-ld:Example:tenant1.
We will connect to the respective database during runtime based on the tenant provided through http headers.

example:

curl -X POST \
 http://localhost:9090/ngsi-ld/v1/entities/ \
 -H 'Accept: application/ld+json' \
 -H 'Content-Type: application/json' \
 -H 'NGSILD-Tenant: urn:ngsi-ld:Example:tenant1' \
 -d '{
       "id": "urn:ngsi-ld:Vehicle:",
       "type": "Vehicle",
       "brandName": {
               "type": "Property",
               "value": "Test"
       },
       "speed": {
               "type": "Property",
               "value": 80
       }
}

Thanks,
Amit.

**Comment by subhommitra** [comment]
Hey Amit, thanks for writing back. Few follow up questions:

-  Is there any authorisation/authentication involved when reading from the different tables for tenants, for e.g. with a GET request?
-  I can see from the codebase that based on the value of the NGSILD-Tenant key, you are creating new database if it doesn't already exist; is there any other way of creating tenants?
- Can we update/manage/delete tenants?

**Comment by ScorpioBroker** [comment]
Hi,

currently we are supporting an oauth integration on the gateway level. Most OAuth solution allow to configure access based also based on headers. 
We are not changing credentials on the database access with a different tenant. Generally speaking i would not expose the database to the outside but only the gateway. 
NGSI-LDs tenant as the spec defines it is really only meant for data separation to make sure no one accidently overrides content. A proper security setup does require a configured oauth server.

At the moment there is no other way to manage tenants via an api since the ngsi-ld spec only defines this dynamic behaviour as we have implemented. This could be something to consider but to be quite honest we are currently busy with moving along the new spec versions so don't count on it appearing soon.

**Comment by subhommitra** [comment]
Thank you very much for your answers. Really appreciate it.
