### ISSUE TITLE
Possible JSON-LD compaction/expansion bug when using user defined time properties

### ISSUE THREAD

**Issue by Blobonat** [ScorpioBroker/ScorpioBroker#325]
Following the official example of the NGSI-LD API v.1.3.1 spec in section C.6 (Date Representation) I tried to create and read back an entity with a user-defined time property.

My entity with the custom time property `constructionDate` during creation looks like this:
```
     {
        "id": "urn:ngsi-ld:RoadSegment:segment1",
        "type": "RoadSegment",
        "totalLaneNumber": {
            "type": "Property",
            "value": 2
        },
        "constructionDate": {
            "type": "Property",
            "value": {
                "@type": "Date",
                "@value": "2020-09-14"
            }
        }
    }
```
During creation I provide the following custom `@context` via the Link-Header (<MY_URL>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"):
```
{
    "@context": {
        "RoadSegment": "https://example.com/RoadSegment",
        "constructionDate": {
            "@id": "https://example.com/constructionDate",
            "@type": "https://uri.etsi.org/ngsi-ld/Date"
        },
        "totalLaneNumber": "https://smartdatamodels.org/totalLaneNumber"
    }
}
```

The entity gets successfully created, but when I try to read it providing the same `@context` the `constructionDate`-property won't get compacted (also note the missing `@` in `type": "Date"`):
```
     {
        "id": "urn:ngsi-ld:RoadSegment:segment1",
        "type": "RoadSegment",
        "totalLaneNumber": {
            "type": "Property",
            "value": 2
        },
        "https://example.com/constructionDate": {
            "type": "Property",
            "value": {
                "type": "Date",
                "@value": "2020-09-14"
            }
        }
    }
```

This behavior seems to be inconsistent.

---

I tested it with `scorpiobroker/scorpio:scorpio-aaio-no-eureka_2.1.20`

**Comment by ScorpioBroker** [comment]
Hi,
i tested this on the ld-playground (json-ld ref impl) https://tinyurl.com/29leet34 and it gives exactly the same behaviour. I can see the the inconsistency but i think scorpio is doing what it should. Having no at in there so just 
`"https://example.com/constructionDate": {
            "type": "Property",
            "value": {
                "type": "Date",
                "value": "2020-09-14"
            }
        }`
is consistent as alternative. 
I fear the core context defining type: @type ensures that it always gets compacted back to type. So this inconsistency is maybe not removable.

**Comment by Blobonat** [comment]
Hi, thanks for the feedback. Haven't thought of testing it with the JSON-LD Playground :) Still a bit weird that `https://example.com/constructionDate` won't get replaced by `constructionDate` in JSON-LD...

**Comment by ScorpioBroker** [comment]
Hi,

oh yes that as well :-) ... i was actually looking at @type and @value coming back differently and didn't even see this first ... 
anyways ... you are not getting back constructionDate because your @context defines https://example.com/constructionDate as type Date but it is type Property so the compacting doesn't find it like this. If you define only "constructionDate": "https://example.com/constructionDate" that works but defining the type like you did doesn't really work because ngsi-ld requires this to be type Property (or relationship etc).

**Comment by Blobonat** [comment]
I followed the example of the NGSI-LD Spec v1.3.1 (Page 193):
> The following example shows how to represent time values (Date, Time, or DateTime) in NGSI-LD using the syntax offered by JSON-LD. User-defined Properties whose value is a time value (Date, DateTime or Time) are defined as Property, not as TemporalProperty, and are serialized in NGSI-LD use the @value syntax structure, as shown by the example below:

```
{
"id": "urn:ngsi-ld:Vehicle:B9211", 
"type": "Vehicle", 
"testedAt": { 
  "type": "Property", 
  "value": { 
    "@type": "DateTime", 
    "@value": "2018-12-04T12:00:00Z" }
}, 
"@context": [ 
  "http://example.org/ngsi-ld/latest/vehicle.jsonld", 
  "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.3.jsonld" 
]
}
```

with `@context`:
```
"testedAt": {
"@type": "https://uri.etsi.org/ngsi-ld/DateTime", 
"@id": "http://example.org/test/P1"
}
```

I am quite new to NGSI-LD so I don't know whether this format is actually agreed on.

**Comment by ScorpioBroker** [comment]
Oh that should be addressed if it's in the appendix of the spec. 
So basically there is currently one user settable datetime for entities/attributes provided by the spec which is observedAt. That you can just set with 
`"observedAt": "2018-12-04T12:00:00Z"`
This is what i would just use for most cases tbh.  If you need an entry like the testedAt you can not do it like C6 suggests since compacting will look for something like this `"http://example.org/test/P1": {
"@type": "https://uri.etsi.org/ngsi-ld/DateTime", 
"@value": "<somedate>"
}`
which it just doesn't find. 

Now i would suggest to only define the full uri for testedAt and don't worry about the type definition inside of value (you can basically free form there with json as you like) 
Or if you really don't care that much about @context (i mean it's a good tool to allow interoperability between different parties but there is also cases where you really don't care about how something gets expanded and compacted you just want it as you provided it) don't provide any in the first place. Scorpio will happily prefix everything with a default prefix coming from the ngsi core context (https://uri.etsi.org/ngsi-ld/default-context/) 
And even if you decide to use an @context later on for queries or so you can still define it to be "mynewname": "https://uri.etsi.org/ngsi-ld/default-context/myoldname" and it works. Not really something i would suggest if you are planing to use smart data models or anything like this but in some use cases it's just what's needed. 


@martin-p-bauer could you have a look at this. i checked it's still present 1.5.1. The example should be fine it the testedAt definition in the @context is changed.

**Comment by martin-p-bauer** [comment]
Yes, sorry, this is a bug in the specification. The proposed @context cannot work with NGSI-LD in normalized representation as it tries to coerce the JSON value of testedAt to be of type DateTime, but actually it is of type Property (due to reification), so it will not compact properly. If you were to use the same @context with simplified representation, the JSON value would be a DateTime and thus it would work.

There is nothing we can do about the type:@type problem, because this mapping is given in the core @context and it is used for compaction in all places in the document. The reason was that in the predecessor of NGSI-LD, which was NGSIv2, "type" was used to for entity type and at the time it was decided to keep as close as possible to NGSIv2 there, thus the mapping was added ...

**Comment by Blobonat** [comment]
Thanks for the clarification. Should the normalized NGSI-LD form for DateTime-attributes as mentioned in the API specification still be used?

```
{
"id": "urn:ngsi-ld:Vehicle:B9211", 
"type": "Vehicle", 
"testedAt": { 
  "type": "Property", 
  "value": { 
    "@type": "DateTime", 
    "@value": "2018-12-04T12:00:00Z" }
},
```

Or should the DateTime-string be directly assigned to `value`?
```
{
  "id": "urn:ngsi-ld:Vehicle:B9211", 
  "type": "Vehicle", 
  "testedAt": { 
   "type": "Property", 
   "value": "2018-12-04T12:00:00Z" 
   }
}
```

I would probably choose a `@context` like `"testedAt": "http://example.org/testedAt"` in both cases.
