### ISSUE TITLE
Build fail for quarkus-release/3.0.0 Branch due to missing dependency

### ISSUE THREAD

**Issue by yshashix** [ScorpioBroker/ScorpioBroker#335]
- I was trying to build quarkus-release/3.0.0 branch with command : <mvn clean package -DskipTests>, but it fails due to missing BouncyCastle dependency as attached image.

I solved it by adding dependency on Common-> pom.xml as below:
         ""    <dependency>
                        <groupId>com.guicedee.services</groupId>
                        <artifactId>bouncycastle</artifactId>
                        <version>1.2.2.1-jre17</version>
                </dependency>
   """
- There was a warning message as well as below:
[WARNING] [io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor] Quarkus detected the need for Mutiny reactive programming support, however the quarkus-resteasy-mutiny extension was not present. Reactive REST endpoints in your application that return Uni or Multi will not function as you expect until you add this extension. Endpoints that need Mutiny are: eu.neclab.ngsildbroker.entityhandler.controller.EntityBatchController{io.smallrye.mutiny.Uni<org.jboss.resteasy.reactive.RestResponse<java.lang.Object>> createMultiple(io.vertx.core.http.HttpServerRequest request, java.lang.String payload)},

Which I solved by adding dependency in BrokerParent->pom.xml as below:
      <dependency>
                        <groupId>io.quarkus</groupId>
                        <artifactId>quarkus-resteasy-mutiny-common</artifactId>
                        <version>2.13.0.Final</version>
                </dependency>

# Note: I am not sure if these are correct fixes, if not please provide us proper fix and a way to build  Scorpio broker using quarkus

![Build failed scorpio](https://user-images.githubusercontent.com/86843454/191918522-067bb78a-d084-4111-b284-8aebe5754adf.png)

**Comment by ScorpioBroker** [comment]
Hi,

don't worry about the warning there. This is because in our Commons we are sharing some resteasy related code between modules, the resteasy dependencies are loaded in from the other modules which actually use the shared code. 

The error you are getting is caused by the kubernetes plugin which we wanted to use to generate helm charts. We only later realized that it does attempt much more and so can be a problem during the build phase. That's also why we removed it for now as a dependency. That would be the fix to remove that dependency.
Or what i would recommend is to switch to a 3,0.1 release branch or https://github.com/ScorpioBroker/ScorpioBroker/tree/development-quarkus which is our master for quarkus.

For building scorpio 

We have two main build/quarkus profiles kafka and in-memory. 

in-memory is only usable for building the all-in-one-runner in variant where it doesn't use kafka but everything in memory. Great for edge devices or anything that doesn't need multiple instances. 

kafka is than for everything else. 

the mvn command would be 
mvn clean package -DskipTests -Din-memory -Pin-memory -Dquarkus.profile=in-memory
mvn clean package -DskipTests -Dkafka -Pkafka -Dquarkus.profile=kafka

we are currently working on the documentation. but you can have a look in the github action for the release 
https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/.github/workflows/release-java.yml
there is a step build-java(-kafka) which is how we are building for our releases.

**Comment by yshashix** [comment]
Thanks for your feedback. It's helpful
