### ISSUE TITLE
Link header does not support multiple values

### ISSUE THREAD

**Issue by lauramartingonzalezzz** [ScorpioBroker/ScorpioBroker#368]
Hi,
We were trying to send multiple values through the Link header and ran into a problem.

According to RFC 8288: Web Linking, this should be done as follows:
```
Link: </TheBook/chapter2>;
      rel="previous"; title*=UTF-8'de'letztes%20Kapitel,
      </TheBook/chapter4>;
      rel="next"; title*=UTF-8'de'n%c3%a4chstes%20Kapitel
```
i.e. separate the different values with a comma.

However, the current Scorpio implementation does not support this, but in order to be able to add multiple values, a Link header must be added for each of them. Following the same example, it would be: 
```
Link: </TheBook/chapter2>; rel="previous"; title*=UTF-8'de'letztes%20Kapitel
Link: </TheBook/chapter4>; rel="next"; title*=UTF-8'de'n%c3%a4chstes%20Kapitel
```
Some services do not allow sending two of the same headers, so it would be necessary for Scorpio to support the official RFC format. 

Kind regards, 
Laura

**Comment by amitrnec** [comment]
Hi,
If you are trying to send multiple @context link so that is not allowed according to json-ld spec.

Thanks,

**Comment by ScorpioBroker** [comment]
Hi,

As Amit pointed out basically Scorpio will anyways only make use of the Link header if it's with the link relationship <http://www.w3.org/ns/json-ld#context> and that one can only be one (json-ld spec http://www.w3.org/TR/json-ld/ or C. 8 in the ngsi-ld spec) ... 

That being said we currently allow you to give in multiple links with context and use them (@amitrnec  sorry i was wrong there just checked)... but this is a bug on our side which we will fix anytime soon. It is a bit unfortunate because technically nothing stops us from allowing multiple contexts like this but the JSON-LD spec is pretty clear on that. 

So depending on the operation you want to do and if this is about multiple contexts you should consider putting the '@context' in your payload and make it content-type application/ld+json or use the entityOperations/query for queries.
Or for the time being provide another remote '@context' which has links two both other contexts.

There is a feature coming in from ngsi-ld to remedy this situation a bit so that brokers can hold '@context' so that you can don't need another webserver but it's not within the next months that we will start implementing this. But it is on our road map.
Any other Link we would be disregarded anyway.
