### ISSUE TITLE
Batch operations fail in AAIO container

### ISSUE THREAD

**Issue by anyname2** [ScorpioBroker/ScorpioBroker#41]
When trying to execute batch operation it fails with Internal Server Error when running AAIO container.

```
POST /ngsi-ld/v1/entityOperations/create
```

Error in the logs:
```

com.netflix.zuul.exception.ZuulException: Forwarding error
...
Caused by: com.netflix.client.ClientException: Load balancer does not have available server for client: ENTITY-MANAGER
```

**Comment by ScorpioBroker** [comment]
Hi,
I'm editing the readme at the moment since this is a bit complex with the profiles and what to start ... if you just use the docker container all should just work as it is starting the gateway with correct profile. If you want to run it outside with just the AllInOnRunner.jar you need to run the the gateway.jar with the profile aaio (or aio as those don't differ at the moment).
java -jar gateway.jar -Dspring.profiles.active=aio

**Comment by anyname2** [comment]
I was using AAIO docker container built from latest source and got the error described.

**Comment by ScorpioBroker** [comment]
oh ok will check that

**Comment by ScorpioBroker** [comment]
hi fixed the yml file for the gateway... did change the wrong one initially
