### ISSUE TITLE
Large Batch operation returns timeout error, but creates entities after a long delay (25 minutes)

### ISSUE THREAD

**Issue by anyname2** [ScorpioBroker/ScorpioBroker#43]
**Description**

When trying to create a large number (~5500) of entities, scorio responds with timeout error message after 60 seconds. After the response is sent, this [initialLog.txt](https://github.com/ScorpioBroker/ScorpioBroker/files/3875127/initialLog.txt) is written and then the logs are flooded with these 2 messages:
```
scorpio_1    | 2019-11-21 14:29:32.951  WARN 10 --- [o-27015-exec-33] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' not supported]
scorpio_1    | 2019-11-21 14:29:32.952  WARN 9 --- [io-9090-exec-90] o.s.c.n.z.f.r.s.AbstractRibbonCommand    : The Hystrix timeout of 60000ms for the command aio-runner is set lower than the combination of the Ribbon read and connect timeout, 240000ms.
```

No entities are created at the time the reponse is returned. But are created ~25 minutes later when the logs start to be flooded with messages similar to [log.txt](https://github.com/ScorpioBroker/ScorpioBroker/files/3875069/log.txt). The messages were still being printed an hour later.

**Reproduction steps**
```jsonnet
POST /ngsi-ld/v1/entityOperations/create
```

Sample request is attached: [request.txt](https://github.com/ScorpioBroker/ScorpioBroker/files/3875001/request.txt).

**Expected Behaviour**

It should identify that the request contains too many entities to handle in a single request and return 413 status code (without waiting for 60 seconds). 

What is the number of entities a user can safely put into a single request and expect entities to be available immediately after receiving the response?

**Current response:**

```json
{
  "timestamp": "2019-11-21T13:39:31.112+0000",
  "status": 500,
  "error": "Internal Server Error",
  "message": "TIMEOUT"
}
```

**Comment by ScorpioBroker** [comment]
Hi,

Since this depends on a few variables it's impossible for me to tell this generally, so i made this now configurable option for each operation
batchoperations:
  maxnumber:
    create: 1000
    update: 1000
    upsert: 1000
    delete: 1000
this very much depends on your hardware how much this can be. 
Additionally you can also put a custom timeout on the gateway which will also influence the number of entities. please see here (https://cloud.spring.io/spring-cloud-gateway/reference/html/#http-timeouts-configuration).

if any of the batch maxnumber entries is not set or set to -1 it will again just try to handle it and might timeout.
