### ISSUE TITLE
query language does not directly support filtering based on 2 or more attributes applied to the same object within an array

### ISSUE THREAD

**Issue by sluFicodes** [ScorpioBroker/ScorpioBroker#547]
We want to retrieve all usages that have an attribute productId with the value: <i>urn:ngsi-ld:product:233ad12e-fcbd-475e-901d-cf671f6d77f5</i> but there are some usages with an attribute called 'valorac' that has the same value.
<b>Entity we want to retrieve:</b>
```
{
        "id": "urn:ngsi-ld:usage:e971f498-ce62-4db2-9a22-7a436eb03414",
        "usageCharacteristic": {
            "type": "Property",
            "value": [
                {
                    "name": "productId",
                    "value": "urn:ngsi-ld:product:233ad12e-fcbd-475e-901d-cf671f6d77f5"
                },
                {
                    "name": "temperatura (Cº)",
                    "value": 1
                }
            ]
          }
    }
 ```
<b>Entity we want to filter out:</b>
``` 
{
        "id": "urn:ngsi-ld:usage:a721d071-3a69-4c1b-a3a2-3e0fd4e60c29",
        "usageCharacteristic": {
            "type": "Property",
            "value": [
                {
                    "name": "productId",
                    "value": "urn:ngsi-ld:product:233ad12e-fcbd-475e-901d-cf671f6d77f6"
                },
                {
                    "name": "valorac",
                    "value": "urn:ngsi-ld:product:233ad12e-fcbd-475e-901d-cf671f6d77f5"
                },
                {
                    "name": "temperatura (Cº)",
                    "value": 1
                }
            ]
        }
    }
```

The best approach we have done to query this is the following: 
```?limit=1000&q=usageCharacteristic[value]=="urn:ngsi-ld:product:233ad12e-fcbd-475e-901d-cf671f6d77f5";usageCharacteristic[name]=="productId"```

But this query does not fulfill all the requirements we want when filtering.
This query only checks if, in the usageChacterictic array, there are some objects with a value <b>"urn:ngsi-ld:product:233ad12e-fcbd-475e-901d-cf671f6d77f5"</b> AND a name <b>productId</b> but it does not check exactly if both conditions are in the same object, it only checks if the list meets the conditions that there is at least one object with that value and at least the same or <b>another object</b> with that name in the list.

**Comment by ScorpioBroker** [comment]
hi so this is a bit of a general issue in my understanding. the ngsi-ld spec does specify the language to check for existence and optional comparison and it doesn't provide a way to index an array like this. it basically says if any of the members of a list fulfill the q query it's true so unfortunately even doing usageCharacteristic[name]!="valorac" will not filter it out because some of the members are still true. so you might consider remodeling and adding something like a data type which can always be compared or you can ask for usageCharacteristic[name]=="valorac" and use that to filter you result in post processing. we can try to suggest something to etsi isg cim like adding a all of the members have to full fill a query or actual indexes of for an array but this might not be successful and will take time.

**Comment by ScorpioBroker** [comment]
Hi,

this was indeed a bug on our side /ngsi-ld/v1/entities?type={{entityTypeTBF}}&q=usageCharacteristic[value]=="urn:ngsi-ld:product:233ad12e-fcbd-475e-901d-cf671f6d77f5";usageCharacteristic[name]=="productId";usageCharacteristic[name]!="valorac" will now provide the expected result.
