### ISSUE TITLE
Expansion/Compaction of an enumerated value

### ISSUE THREAD

**Issue by jason-fox** [ScorpioBroker/ScorpioBroker#55]
I create an entity:

```console
curl -L -X POST 'http://localhost:9090/ngsi-ld/v1/entities/' \
-H 'Content-Type: application/ld+json' \
--data-raw '{
    "id": "urn:ngsi-ld:Building:store001",
    "type": "Building",
    "category": {
    	"type": "Property",
        "value": ["commercial"]
    },
    "address": {
        "type": "Property",
        "value": {
            "streetAddress": "Bornholmer Straße 65",
            "addressRegion": "Berlin",
            "addressLocality": "Prenzlauer Berg",
            "postalCode": "10439"
        },
        "verified": {
			"type": "Property",
			"value": true
		}
    },
    "location": {
        "type": "GeoProperty",
        "value": {
             "type": "Point",
             "coordinates": [13.3986, 52.5547]
        }
    },
    "name": {
        "type": "Property",
        "value": "Bösebrücke Einkauf"
    },
    "@context": [
        "https://schema.lab.fiware.org/ld/context"
    ]
}'
```

### Get a single entity by id as JSON supply @context

```console
curl -L -X GET 'http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Building:store001' \
-H 'Accept: application/json' \
-H 'Link: <https://schema.lab.fiware.org/ld/context>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"'
```
`category` attribute is not correctly compacted:

```json
"https://uri.fiware.org/ns/data-models#category": {
    "type": "Property",
    "value": "commercial"
  }
```

expected:

```json
"category": {
        "type": "Property",
        "value": [
            "commercial"
        ]
    },
```

(Actually the Scorpio reduction of the array is correct here  - it is just the attribute name that has not been altered.)

## Get a single entity as JSON - no context supplied

```console
curl -L -X GET 'http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:Building:store001' \
-H 'Accept: application/json'
```

value of the `category` attribute is not correctly expanded. Note that commercial is defined as `@vocab`

```json
"https://uri.fiware.org/ns/data-models#category": {
    "type": "Property",
    "value": "commercial"
  }
```

expected:

```json
"https://uri.fiware.org/ns/data-models#category": {
        "type": "Property",
        "value": [
            "https://uri.fiware.org/ns/data-models#commercial"
        ]
    },
```

Tested AAIO 0.9.5

**Comment by ScorpioBroker** [comment]
Hi,
i can see the problem with the missing array and will try to address this (ambiguous @context entry strikes again). but why are you expecting your value to be expanded somehow? 

I made a few tests on the json-ld playground at there seems to be a problem with the fiware context for category. It never compacts back like this.
Please see the attached screenshots even with only the fiware context this never compacts back properly. Also see how the array is never protected since the contexts are ambiguous here. If you add another entry to the array it will return as array but one entry arrays are never compacted back in an entry if its not explicitly declared as list.

![fiwareonly](https://user-images.githubusercontent.com/55130839/75876519-21591880-5e16-11ea-97a2-ef92c0817b74.png)
![ngsi+fiware](https://user-images.githubusercontent.com/55130839/75876521-21f1af00-5e16-11ea-8481-16e843b87950.png)


after some more playing around i think the @vocab is just wrongly used there because when i add something to category (see picture) like categoryasd it will compact back to categoryasd.

![vocab](https://user-images.githubusercontent.com/55130839/75877005-02a75180-5e17-11ea-9b17-611661c7fa1c.png)

**Comment by jason-fox** [comment]
if I supply the `@context`  -properly compacted  (i.e. not `https://uri.fiware.org/ns/data-models#category` ) would be correct.

``json
"category": {
        "type": "Property",
        "value":  "commercial"
    }
```

unless the attribute is defined as an `@set` or `@list`, in which case value should be an array of one.

Properly expanded  (if I fail to supply the `@context` )

```json
"https://uri.fiware.org/ns/data-models#category": {
        "type": "Property",
        "value":  "https://uri.fiware.org/ns/data-models#commercial"
    },
```

The point being that if `category` is defined as:

```jsonld
"category": { 
      "@id" :"fiware:category",
      "@type": "@vocab"
    }, 
```

Then  the `value` is an array of **enumerations** - which can be expanded and compacted in the usual manner.

**Comment by ScorpioBroker** [comment]
The point being that if category is defined as:

"category": { 
      "@id" :"fiware:category",
      "@type": "@vocab"
    },
Then the value is an array of enumerations - which can be expanded and compacted in the usual manner.

------------------------
I don't think that is the case. As far as i understand the json ld spec, this only means that every key which starts with category will be prefixed with fiware:category. Also thats how the playground does it which is the reference impl. for jsonld. Have a look at the first picture which only uses the datamodel context the values are never touched like this.

**Comment by jason-fox** [comment]
> I don't think that is the case. As far as i understand the json ld spec ...

I'm referring to the secondary meaning of `@vocab` as defined here:  https://github.com/lanthaler/JsonLD/issues/31

> The @vocab keyword has a second meaning which is not mentioned in the
json-ld spec, only in the api. If used as a value of @type in the
context, it says that the corresponding attribute value must be
expanded to an IRI.

Hence if I create `category:  commercial`.    these should be expanded.

**Comment by ScorpioBroker** [comment]
Type Coercion only works on raw string values which we don't have here.
https://www.w3.org/TR/json-ld/#type-coercion
> Type coercion allows someone deploying JSON-LD to use **string** property values and have those values be interpreted as typed values by associating an IRI with the value in the expanded value object representation.
I've tested it on the playground (see pics). Even a low complexity already denies that. It doesn't even work with numbers but really only with either strings or an array of strings.
And what than happens since this is not a string it falls back to using it as prefix with.

![stringonly](https://user-images.githubusercontent.com/55130839/75903529-000e2180-5e42-11ea-8cfc-2aa71f12018a.png)
![complex](https://user-images.githubusercontent.com/55130839/75903532-013f4e80-5e42-11ea-8a73-c6ebde7ba1b1.png)

**Comment by martin-p-bauer** [comment]
I checked the referred example, which works in the playground, and after having a detailed look, I noticed the difference: you can use the @vocab in the case of directly referring to the JSON value, so in the example you have  "delivery": "RENT" and the @vocab is defined for delivery. Now, this is not the case for us: you have  "category" whose JSON value is a JSON object (of type Property) and that JSON object has a pair "value": "commercial" (or "value": ["commercial"]) - with the definition you made, you cannot go inside the value element of the Property JSON object and apply to its JSON value. For testing I adapted the @context definition in the playground, replacing the definitions of value, category and commercial with the following: 
      "value": {
            "@id" : "https://uri.etsi.org/ngsi-ld/hasValue",
     		"@type" : "@vocab"
      },
       "category": "https://uri.fiware.org/ns/data-models/category",
       "commercial": "https://uri.fiware.org/ns/data-models#commercial",
and this gives what you would have liked to see (apart from the fact that for a single value there is no array, but that issue has already been discussed):
  "category": {
    "type": "Property",
    "value": "commercial"
  }
ONLY, we cannot generally redefine "value" in this way, as you might want to use a particular string as a value and if that accidentally also exists as a definition in the @context it would be replaced by the URI, which is not valid.

**Comment by ScorpioBroker** [comment]
Since is more about the use of the core context combined with other contexts and not a scorpio issue i'll close this. Let's continue this via email
