### ISSUE TITLE
Wrong response code generated for create entity request, when kafka service is down.

### ISSUE THREAD

**Issue by MayankMag** [ScorpioBroker/ScorpioBroker#76]
Scorpio Broker generates wrong response code when a POST request for create entity is made on it while Kafka Server is down. Ideally it should not  give Response(201 Created), when entity is not created in the database.

Pre-Requisite: Kafka service is down.
Expected Response: Kafka service is down.
Actual Response: 201 Created
Response Body: <Entity-ID>

**Comment by ScorpioBroker** [comment]
Hi,
thanks for the report. I'll have to investigate a bit how to handle this properly since we are sending these messages in an asynchronous manner to avoid blocking on the http interface. Hence it's a bit hard to capture an error. At the moment my train of thought is rather in the direction of keeping messages until kafka comes back up than erroring out.
Benni

**Comment by ScorpioBroker** [comment]
We have changed the way to store entities now fundamentally so i'm closing this here.
